version: "3.8"
networks:
  project_network:
    name: ${PROJECT_NAME}_network
services:
#  certbot:
#    container_name: ${PROJECT_NAME}_certbot
#    image: certbot/certbot
#    depends_on:
#      - nginx
#    volumes:
#      - /etc/letsencrypt:/etc/letsencrypt
#      - /var/lib/letsencrypt:/var/lib/letsencrypt
#    command: certonly --webroot --webroot-path=/var/lib/letsencrypt --email ${CERTBOT_EMAIL} --agree-tos --no-eff-email --staging --domains ${NGINX_SERVER_NAME}
  nginx:
    container_name: ${PROJECT_NAME}_nginx
    image: nginx:alpine
    env_file:
      - .env
    ports:
      - "80:8081"
      - "443:8082"
    depends_on:
      - php-fpm
    volumes:
      - ./nginx/templates/:/etc/nginx/templates
      - ./../:/var/www/html
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    networks:
      - project_network
  php-fpm:
    container_name: ${PROJECT_NAME}_php_fpm
    build:
      context: ./php-fpm/
      dockerfile: Dockerfile
      args:
        - UID=${UID}
        - GID=${GID}
    image: ${PROJECT_NAME}/php-fpm
    depends_on:
      - mysql
    env_file:
      - .env
    ports:
      - "9000:9000"
    volumes:
      - ./../:/var/www/html
    networks:
      - project_network
  mysql:
    container_name: ${PROJECT_NAME}_mysql
    image: mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      - project_network
